### ISSUE TITLE
[Question] Help getting started - CIMTool fails to load

### ISSUE THREAD

**Issue by TheTimKiely** [CIMug-org/CIMTool#10]
Hi,
I'm completely new to CIMTool.  I followed the instructions to create a deployment.  But when I run the CIMTool.exe created by my deployment, the application crashes after the "Select a directory as workspace" dialog.
I've attached the log file.
Are there dependencies I should be aware of?  Is a certain version of Java required?

Thanks,
Tim
[CIMTool.log](https://github.com/CIMug-org/CIMTool/files/7389892/CIMTool.log)

**Comment by tviegut** [comment]
Tim,

I apologize that I haven't responded to either of the two issues/questions you've posted.  We have a general CIM UCAIug gmail account we use for the primary org and just discovered that email notifications were getting swallowed and not forwarded on.  So no one was notified that issues were created.  

I'd love to assist you and given the length of time you've had to wait I'd be more than happy to contact you directly and walk you through anything you might need help with.  It sounds like our primary README page needs to be tweaked a bit as it appears there's some confusion.  We have separate link for end-users that just want to download the latest build (no dev environment setup or deployment) and provided a ZIP file that you simply extract and run.  As for the dev environment setup instructions that is only needed if someone is going to be doing actual development for CIMTool.  If you are interested in contributing I can walk you through that.  

I'll be sure to update the README so that things are clearer in the future for anyone checking out the site.

Regards,

Todd Viegut

**Comment by TheTimKiely** [comment]
Hi Todd,
I really appreciate your offer and would like to take you up on it.
I am interested in contributing.  I have been writing code for many years,
but I haven't used Eclipse RCP previously.
Getting started with CIMTool, I'm having trouble configuring the
dependencies so that I can
1. Run the CIMTool in the Eclipse debugger
2. Configure the Product wizard to produce a full, working deployment

Please let me know what would be the best way for you to connect.

Thanks again!
-Tim
